language: java
jdk:
  - oraclejdk8
env:
    global:
        - JAVAREPL_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
        - JAVAREPL_REPOSITORY="albertlatacz/java-repl"
        - secure: "bIFU+VgbcIJ5DmsXkoxTaLGI40uIyWdTFnco7FaJLoJLwLJSake4jemFv5SI\nJaSFVINBXA+Xn/qqHmFfWVr2fKsAevwRfkkIuTM1QMlN2TOMkCwOrz6mYA3f\nxjh+oKXUzNutZTHSyoCyZ72uHSJ33TlPWHU+OToS4AYxf8LrTYI="
        - secure: "O0xTkW+WBNWT0a44u7XRpm0vp0q04ZFv/ovmPX6nm3fRokuiHMoRaL1l7r1K\nLF9ow3n+Ncsl64XRJNv2rjKVrxb19GtZQjxnHqi6bW2FSnoTEJsfvIjgMOwh\nrOHL9MUP61idRqN15ki0qYsmZ8t3xN9rw04fJLGZn73Oy0uRSGI="
        - secure: "C5j0sZWXhfOoaVYyylyM7aJsjUSBbiIkW2GpAhODIrp/E5l297TymomFOCOTZSL1xF5V4RYt6jc7db+Qri5ryeHd0IIYMNWqcmni4rChtKp4b2F4qh+eqwre8RW5hONOcByZTQDvo+m3SCTuoTWcIM/UIhQIGovSPtYmqjQlSwI="
        - secure: "fpuaeSvHiDRtUGHRuCkaZOglaE8IujaCXjSShYP78kxaZUOkHCY6meGmk2YRB6nKTs80lpiQCGFOmtcdEOsCRt2kQXuzJR6NkcG8JEYbdD36G0zR/GpeZ38o3lZqd7Xy1FEGwTgMi0Wy699ZvSoBP1xtGz8A7f8G9ROV7E81gdw="



sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer

branches:
    only:
        - master

services:
  - docker

script:
  - gradle -Pversion=$JAVAREPL_BUILD_NUMBER clean build shadowJar

deploy:
    provider: releases
    api_key:
        secure: "Dlvp//L9a/9bHgtTZPWy+tTbsokq5f3fhobmR1tBtEQUiuOl0dl5nzVOq1tBb0AwPBmTudkBIwH1DW64WCnZnGUatiVznfEydGgCzaW8hNeg9S2iatNIjVjqWXrR/Id+Vg8gGoDomLltPL5qb5UBhdpiOT9Te/GH5/hRUw0NpvI="
    file: "build/libs/*.jar"
    file_glob: true
    skip_cleanup: true
    on:
        branch: master
        repo: $JAVAREPL_REPOSITORY


after_deploy:
    - sh bin/push-to-docker-hub.sh $DOCKER_HUB_USERNAME $DOCKER_HUB_PASSWORD $JAVAREPL_REPOSITORY $JAVAREPL_BUILD_NUMBER

after_success:
    - sh bin/set-tags.sh



